param(
    [string]$ProjectRoot = (Get-Location).Path,
    [string]$OutputPath = (Join-Path (Get-Location).Path "chatgpt-advisory.md"),
    [string]$BackupScriptPath = (Join-Path (Get-Location).Path "backup.ps1"),
    [switch]$IncludeSensitiveDetails,
    [int64]$LargeThresholdMB = 256
)

$ErrorActionPreference = "Stop"

# Preference mining script generated by ChatGPT.
# Goal: inspect likely user-defined preference/config locations and produce
# chatgpt-advisory.md without copying files and without printing secrets.
#
# It classifies candidate paths as:
# - AlreadyCovered: appears in backup.ps1
# - Found: exists on this computer
# - Sensitive: likely contains credentials/tokens/private keys
# - Large: larger than LargeThresholdMB
#
# It intentionally favors metadata and filenames over file contents.

function Expand-CandidatePath {
    param([Parameter(Mandatory)][string]$Path)
    [Environment]::ExpandEnvironmentVariables($Path)
}

function ConvertTo-MarkdownSafe {
    param([AllowNull()][string]$Text)
    if ($null -eq $Text) { return "" }
    return ($Text -replace '\|', '\|' -replace "`r?`n", " ")
}

function Get-DirectorySize {
    param([Parameter(Mandatory)][string]$Path)
    try {
        if (-not (Test-Path -LiteralPath $Path)) { return 0 }
        $item = Get-Item -LiteralPath $Path -Force -ErrorAction Stop
        if (-not $item.PSIsContainer) { return [int64]$item.Length }

        $sum = 0L
        Get-ChildItem -LiteralPath $Path -Recurse -Force -ErrorAction SilentlyContinue |
            Where-Object { -not $_.PSIsContainer } |
            ForEach-Object { $sum += [int64]$_.Length }
        return $sum
    }
    catch {
        return $null
    }
}

function Format-Bytes {
    param([AllowNull()][Nullable[int64]]$Bytes)
    if ($null -eq $Bytes) { return "unknown" }
    if ($Bytes -ge 1GB) { return ("{0:N2} GB" -f ($Bytes / 1GB)) }
    if ($Bytes -ge 1MB) { return ("{0:N2} MB" -f ($Bytes / 1MB)) }
    if ($Bytes -ge 1KB) { return ("{0:N2} KB" -f ($Bytes / 1KB)) }
    return "$Bytes B"
}

function Get-InterestingChildren {
    param(
        [Parameter(Mandatory)][string]$Path,
        [int]$Limit = 30
    )

    if (-not (Test-Path -LiteralPath $Path)) { return @() }

    $noise = @(
        'cache','caches','Cache','GPUCache','Code Cache','CachedData','logs','log','tmp','temp',
        'crashpad','Crashpad','crashes','Crash Reports','updates','blob_storage','Service Worker',
        'DawnCache','ShaderCache','GrShaderCache','__pycache__','node_modules','.git'
    )

    try {
        $item = Get-Item -LiteralPath $Path -Force
        if (-not $item.PSIsContainer) {
            return @($item.Name)
        }

        return @(Get-ChildItem -LiteralPath $Path -Force -ErrorAction SilentlyContinue |
            Where-Object { $noise -notcontains $_.Name } |
            Sort-Object LastWriteTime -Descending |
            Select-Object -First $Limit |
            ForEach-Object {
                if ($_.PSIsContainer) { "$($_.Name)/" } else { $_.Name }
            })
    }
    catch {
        return @()
    }
}

function Read-BackupCoveredPaths {
    param([string]$Path)

    if (-not (Test-Path -LiteralPath $Path)) { return @{} }

    $text = Get-Content -LiteralPath $Path -Raw
    $matches = [regex]::Matches($text, '["''](%[^"'']+)["'']')
    $map = @{}
    foreach ($m in $matches) {
        $raw = $m.Groups[1].Value
        $expanded = (Expand-CandidatePath $raw).TrimEnd('\')
        $map[$expanded.ToLowerInvariant()] = $raw
    }
    return $map
}

function New-Candidate {
    param(
        [Parameter(Mandatory)][string]$Category,
        [Parameter(Mandatory)][string]$Name,
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$Why,
        [ValidateSet("Add","Consider","InventoryOnly","AlreadyCovered","Avoid","Manual")]
        [string]$Recommendation = "Consider",
        [bool]$Sensitive = $false,
        [string]$RestoreNote = "",
        [string]$EvidenceHint = ""
    )

    [pscustomobject]@{
        Category = $Category
        Name = $Name
        Path = $Path
        Why = $Why
        Recommendation = $Recommendation
        Sensitive = $Sensitive
        RestoreNote = $RestoreNote
        EvidenceHint = $EvidenceHint
    }
}

$covered = Read-BackupCoveredPaths -Path $BackupScriptPath

# Candidate list is intentionally broader than current backup.ps1.
# It contains small, usually user-defined state. Large/cache-heavy locations are flagged.
$candidates = @(
    # Core developer identity/state
    New-Candidate "Developer identity" "SSH keys and config" "%USERPROFILE%\.ssh" "SSH keys, host aliases, known_hosts. High-value and usually hand-defined." "AlreadyCovered" $true "Restore before using git/ssh; protect with encryption."
    New-Candidate "Developer identity" "GnuPG" "%USERPROFILE%\.gnupg" "Signing/encryption keys and trust database." "AlreadyCovered" $true "Restore carefully; permissions matter."
    New-Candidate "Developer identity" "Git global config" "%USERPROFILE%\.gitconfig" "Global user.name, aliases, merge/diff tools, credential helpers." "AlreadyCovered" $false
    New-Candidate "Developer identity" "Git credentials" "%USERPROFILE%\.git-credentials" "Possible stored HTTPS credentials/tokens." "AlreadyCovered" $true
    New-Candidate "Developer identity" "Git ignore global" "%USERPROFILE%\.gitignore_global" "Global ignore rules if present." "Add" $false
    New-Candidate "Developer identity" "Git attributes global" "%USERPROFILE%\.gitattributes" "Global line-ending/diff behavior if present." "Add" $false

    # Shells/terminals
    New-Candidate "Shells and terminals" "PowerShell profile folder" "%USERPROFILE%\Documents\PowerShell" "PowerShell 7 modules/profile scripts often live here." "Consider" $false
    New-Candidate "Shells and terminals" "Windows PowerShell profile folder" "%USERPROFILE%\Documents\WindowsPowerShell" "Windows PowerShell 5.1 profile scripts/modules." "Consider" $false
    New-Candidate "Shells and terminals" "Windows Terminal settings" "%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json" "Terminal profiles, colors, fonts, keybindings." "Add" $false
    New-Candidate "Shells and terminals" "Windows Terminal Preview settings" "%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe\LocalState\settings.json" "Preview terminal profiles/settings, if used." "Consider" $false
    New-Candidate "Shells and terminals" "Oh My Posh themes/config" "%USERPROFILE%\.poshthemes" "Custom prompt themes, if not only installed defaults." "Consider" $false
    New-Candidate "Shells and terminals" "Bash rc" "%USERPROFILE%\.bashrc" "User-defined shell initialization." "AlreadyCovered" $false
    New-Candidate "Shells and terminals" "WSL global config" "%USERPROFILE%\.wslconfig" "Global WSL limits/network/systemd behavior." "AlreadyCovered" $false

    # VS Code / AI tools
    New-Candidate "Editors and AI assistants" "VS Code user settings" "%APPDATA%\Code\User\settings.json" "Explicit editor settings." "AlreadyCovered" $false
    New-Candidate "Editors and AI assistants" "VS Code keybindings" "%APPDATA%\Code\User\keybindings.json" "Explicit keyboard customizations." "AlreadyCovered" $false
    New-Candidate "Editors and AI assistants" "VS Code snippets" "%APPDATA%\Code\User\snippets" "Hand-written snippets." "AlreadyCovered" $false
    New-Candidate "Editors and AI assistants" "VS Code Copilot memory" "%APPDATA%\Code\User\globalStorage\github.copilot-chat\memory-tool\memories" "Copilot memory/preferences." "AlreadyCovered" $false
    New-Candidate "Editors and AI assistants" "VS Code extension inventory" "%USERPROFILE%\dev-setup\vscode-extensions.txt" "Small explicit extension list generated by code --list-extensions." "Add" $false "Generate during backup, do not copy extension binaries."
    New-Candidate "Editors and AI assistants" "VS Code profile definitions" "%APPDATA%\Code\User\profiles" "Named VS Code profiles, if used." "Add" $false
    New-Candidate "Editors and AI assistants" "VS Code global storage selected" "%APPDATA%\Code\User\globalStorage" "May contain extension-specific user state; should be mined selectively, not backed up wholesale." "Manual" $false "Review report children; avoid caches and auth blobs unless intentional."
    New-Candidate "Editors and AI assistants" "Codex config" "%USERPROFILE%\.codex" "Codex CLI/agent configuration, auth/session/preferences if present." "Add" $true "Likely sensitive. Back up encrypted only."
    New-Candidate "Editors and AI assistants" "OpenAI config" "%USERPROFILE%\.openai" "OpenAI CLI/API local config if present." "Consider" $true
    New-Candidate "Editors and AI assistants" "Notepad++ config" "%APPDATA%\Notepad++" "Sessions, preferences, user-defined language files." "AlreadyCovered" $false

    # Python/dev tooling
    New-Candidate "Language tooling" "PDM config/cache root" "%APPDATA%\pdm" "PDM config and possibly auth/cache. Prefer config; avoid package caches." "Add" $true
    New-Candidate "Language tooling" "PDM user home" "%USERPROFILE%\.pdm" "Older/alternate PDM state." "Consider" $true
    New-Candidate "Language tooling" "Pyenv-win" "%USERPROFILE%\.pyenv" "Python versions can be large; config/shims useful, versions reinstallable." "Manual" $false "Prefer inventory of installed versions over copying full versions."
    New-Candidate "Language tooling" "pip config" "%APPDATA%\pip\pip.ini" "Custom package indexes/trusted-hosts; may include tokens." "Add" $true
    New-Candidate "Language tooling" "Jupyter config" "%USERPROFILE%\.jupyter" "Notebook/lab config, kernels, server config; may include tokens." "Add" $true
    New-Candidate "Language tooling" "IPython config" "%USERPROFILE%\.ipython" "Profiles/startup scripts." "Add" $false
    New-Candidate "Language tooling" "R user profile" "%USERPROFILE%\.Rprofile" "R startup configuration." "Consider" $false
    New-Candidate "Language tooling" "Renviron" "%USERPROFILE%\.Renviron" "R environment variables; may contain secrets." "Consider" $true
    New-Candidate "Language tooling" "Julia config" "%USERPROFILE%\.julia\config" "Julia startup/config only, not packages/artifacts." "Consider" $false
    New-Candidate "Language tooling" "npm config" "%USERPROFILE%\.npmrc" "NPM registry/token config." "AlreadyCovered" $true
    New-Candidate "Language tooling" "NuGet config" "%APPDATA%\NuGet\NuGet.Config" ".NET package source configuration; may contain tokens." "Add" $true
    New-Candidate "Language tooling" "Cargo config" "%USERPROFILE%\.cargo\config.toml" "Rust registry/build config if present." "Consider" $false

    # Cloud/remote
    New-Candidate "Cloud and remote CLIs" "GitHub CLI" "%USERPROFILE%\.config\gh" "GitHub hosts, auth, aliases." "Add" $true
    New-Candidate "Cloud and remote CLIs" "AWS CLI" "%USERPROFILE%\.aws" "AWS profiles/credentials." "AlreadyCovered" $true
    New-Candidate "Cloud and remote CLIs" "Azure CLI" "%USERPROFILE%\.azure" "Azure CLI profiles/tokens." "AlreadyCovered" $true
    New-Candidate "Cloud and remote CLIs" "Google Cloud SDK" "%USERPROFILE%\.config\gcloud" "gcloud accounts/projects/tokens." "Add" $true
    New-Candidate "Cloud and remote CLIs" "gsutil" "%USERPROFILE%\.gsutil" "gsutil credentials/config." "AlreadyCovered" $true
    New-Candidate "Cloud and remote CLIs" "rclone config" "%APPDATA%\rclone\rclone.conf" "Cloud remote definitions and tokens." "AlreadyCovered" $true
    New-Candidate "Cloud and remote CLIs" "OpenVPN config" "%USERPROFILE%\OpenVPN\config" "User VPN profiles/certs if stored here." "Consider" $true
    New-Candidate "Cloud and remote CLIs" "OpenVPN app config" "%APPDATA%\OpenVPN Connect" "VPN profiles/app state; likely sensitive." "Consider" $true

    # Containers/VMs/databases
    New-Candidate "Containers and virtualization" "Docker client config" "%USERPROFILE%\.docker" "Docker CLI config/auth/contexts." "AlreadyCovered" $true
    New-Candidate "Containers and virtualization" "Docker Desktop app data" "%APPDATA%\Docker" "Often cache/state-heavy; usually avoid unless specific settings matter." "Avoid" $true
    New-Candidate "Containers and virtualization" "Docker Desktop local data" "%LOCALAPPDATA%\Docker" "Usually large internal VM/state/cache; avoid for preference-only backups." "Avoid" $true
    New-Candidate "Containers and virtualization" "VirtualBox global config" "%USERPROFILE%\.VirtualBox" "VM registry/preferences; VM disks are separate and large." "Manual" $false
    New-Candidate "Containers and virtualization" "VirtualBox VMs" "%USERPROFILE%\VirtualBox VMs" "Actual VM disks; large opt-in only." "Manual" $false
    New-Candidate "Containers and virtualization" "pgAdmin config" "%APPDATA%\pgAdmin" "Server registrations/preferences; may include saved passwords depending config." "Add" $true
    New-Candidate "Containers and virtualization" "DBeaver data" "%APPDATA%\DBeaverData" "Database connections, drivers, workspace metadata." "AlreadyCovered" $true
    New-Candidate "Containers and virtualization" "PostgreSQL roaming config" "%APPDATA%\postgresql" "psql history/passfile/certs if present." "Add" $true
    New-Candidate "Containers and virtualization" "psql passfile" "%APPDATA%\postgresql\pgpass.conf" "PostgreSQL saved passwords." "Add" $true

    # Sync/storage tools
    New-Candidate "Sync and storage" "Syncthing local state" "%LOCALAPPDATA%\Syncthing" "Syncthing config/device/folder IDs." "AlreadyCovered" $true
    New-Candidate "Sync and storage" "SyncTrayzor config" "%APPDATA%\SyncTrayzor\config.xml" "SyncTrayzor UI/service settings." "AlreadyCovered" $false
    New-Candidate "Sync and storage" "Synology Drive settings" "%LOCALAPPDATA%\SynologyDrive" "May contain sync task definitions; can be medium/large." "Consider" $true
    New-Candidate "Sync and storage" "Google DriveFS settings" "%LOCALAPPDATA%\Google\DriveFS" "Account/mount metadata. Usually not needed, but may speed restore." "Manual" $true
    New-Candidate "Sync and storage" "OneDrive settings" "%LOCALAPPDATA%\Microsoft\OneDrive\settings" "Account/sync state. Usually reconstructable; settings may help." "Manual" $true

    # Apps installed in your list
    New-Candidate "Applications" "Everything settings" "%APPDATA%\Everything" "Search indexes/settings; current backup covers roaming path." "AlreadyCovered" $false
    New-Candidate "Applications" "Everything service/program data" "%ProgramData%\Everything" "Everything service config/database may live here." "Consider" $false
    New-Candidate "Applications" "FastCopy settings" "%APPDATA%\FastCopy" "Copy presets/preferences." "AlreadyCovered" $false
    New-Candidate "Applications" "WinMerge settings" "%APPDATA%\WinMerge" "Diff tool preferences." "AlreadyCovered" $false
    New-Candidate "Applications" "KDiff3 config" "%USERPROFILE%\.kdiff3rc" "3-way merge tool config." "AlreadyCovered" $false
    New-Candidate "Applications" "Diffuse config" "%USERPROFILE%\.config\diffuse" "N-way diff tool config." "AlreadyCovered" $false
    New-Candidate "Applications" "SumatraPDF settings" "%APPDATA%\SumatraPDF" "Reader preferences and history." "AlreadyCovered" $false
    New-Candidate "Applications" "IrfanView settings" "%APPDATA%\IrfanView" "Viewer preferences/plugins configuration." "AlreadyCovered" $false
    New-Candidate "Applications" "OBS Studio" "%APPDATA%\obs-studio" "Scenes, profiles, plugin config." "AlreadyCovered" $false
    New-Candidate "Applications" "qBittorrent selected config" "%APPDATA%\qBittorrent" "Preferences/categories/watched folders. Avoid BT_backup if not desired." "AlreadyCovered" $false
    New-Candidate "Applications" "Jackett config" "%ProgramData%\Jackett" "Indexer configuration; may contain API keys." "Consider" $true
    New-Candidate "Applications" "yt-dlp config" "%APPDATA%\yt-dlp" "Downloader config if present." "Consider" $false
    New-Candidate "Applications" "gallery-dl config" "%APPDATA%\gallery-dl" "Downloader config; may contain cookies/tokens." "Consider" $true
    New-Candidate "Applications" "Wireshark profile/preferences" "%APPDATA%\Wireshark" "Capture/display profiles and protocol preferences." "Add" $false
    New-Candidate "Applications" "Fiddler settings" "%USERPROFILE%\Documents\Fiddler2" "Rules/certs/captures. Captures may be sensitive/large." "Manual" $true
    New-Candidate "Applications" "Postman data" "%APPDATA%\Postman" "Collections/workspaces/auth if not cloud-synced; can be large." "AlreadyCovered" $true
    New-Candidate "Applications" "WinAuth" "%APPDATA%\WinAuth" "2FA authenticators. Critical and sensitive." "AlreadyCovered" $true
    New-Candidate "Applications" "AutoHotkey scripts common folder" "%USERPROFILE%\Documents\AutoHotkey" "User scripts/hotkeys if stored in the conventional folder." "Add" $false
    New-Candidate "Applications" "PowerToys settings" "%LOCALAPPDATA%\Microsoft\PowerToys" "PowerToys modules/settings/key remaps." "Add" $false
    New-Candidate "Applications" "Sizer settings" "%APPDATA%\Sizer" "Custom window sizes/layouts if present." "Consider" $false
    New-Candidate "Applications" "Sandboxie Plus config" "%USERPROFILE%\Sandboxie-Plus.ini" "Sandbox definitions/settings if present." "Consider" $false
    New-Candidate "Applications" "Sandboxie config" "%WINDIR%\Sandboxie.ini" "System-wide sandbox definitions; requires admin to back up." "Manual" $false
    New-Candidate "Applications" "MSI Afterburner profiles" "%ProgramFiles(x86)%\MSI Afterburner\Profiles" "GPU fan/OC profiles, if customized." "Manual" $false
    New-Candidate "Applications" "RTSS profiles" "%ProgramFiles(x86)%\RivaTuner Statistics Server\Profiles" "Overlay/framerate profiles if installed." "Manual" $false

    # Academic/writing/tools
    New-Candidate "Academic and writing" "TeXstudio settings" "%APPDATA%\texstudio" "LaTeX editor settings/macros." "Add" $false
    New-Candidate "Academic and writing" "TeX Live user tree" "%USERPROFILE%\texmf" "User-installed LaTeX packages/classes/bib styles." "Add" $false
    New-Candidate "Academic and writing" "Pandoc defaults" "%APPDATA%\pandoc" "Pandoc defaults/templates/filters." "Consider" $false
    New-Candidate "Academic and writing" "Jarte settings" "%APPDATA%\Jarte" "Jarte preferences if used." "Consider" $false
    New-Candidate "Academic and writing" "Adobe user settings" "%APPDATA%\Adobe\Acrobat" "Reader/Acrobat user preferences; often large/noisy." "Manual" $false

    # Android
    New-Candidate "Android" "Android user config" "%USERPROFILE%\.android" "ADB keys, repositories.cfg, emulator config. AVDs may be large." "Manual" $true
    New-Candidate "Android" "Android Studio settings" "%APPDATA%\Google\AndroidStudio*" "IDE settings/options. Wildcard is advisory; inspect manually." "Consider" $false
    New-Candidate "Android" "Android SDK" "%LOCALAPPDATA%\Android\Sdk" "Usually large/reinstallable; avoid except custom AVDs/system images." "Avoid" $false
    New-Candidate "Android" "Android AVDs" "%USERPROFILE%\.android\avd" "Custom emulator devices. Large opt-in." "Manual" $false

    # Windows customization
    New-Candidate "Windows customization" "Explorer Advanced registry" "REG:HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" "Explorer/taskbar preferences." "AlreadyCovered" $false
    New-Candidate "Windows customization" "Search registry" "REG:HKCU\Software\Microsoft\Windows\CurrentVersion\Search" "Search/Cortana/Bing preferences." "AlreadyCovered" $false
    New-Candidate "Windows customization" "User environment registry" "REG:HKCU\Environment" "User environment variables." "AlreadyCovered" $false
    New-Candidate "Windows customization" "Machine environment registry" "REG:HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment" "Machine environment variables." "AlreadyCovered" $false
    New-Candidate "Windows customization" "Fonts installed by user" "%LOCALAPPDATA%\Microsoft\Windows\Fonts" "User-installed fonts. Avoid sharing font files publicly; backup privately if licensed." "Manual" $false
    New-Candidate "Windows customization" "Startup folder" "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup" "Explicit per-user startup shortcuts/scripts." "Add" $false
)

$results = @()

foreach ($c in $candidates) {
    $isRegistry = $c.Path.StartsWith("REG:")
    $expanded = if ($isRegistry) { $c.Path } else { Expand-CandidatePath $c.Path }
    $exists = $false
    $size = $null
    $lastWrite = $null
    $children = @()
    $coveredByScript = $false
    $coveredRaw = $null

    if ($isRegistry) {
        $regKey = $c.Path.Substring(4)
        $psRegPath = $regKey -replace '^HKCU\\','Registry::HKEY_CURRENT_USER\' -replace '^HKLM\\','Registry::HKEY_LOCAL_MACHINE\'
        $exists = Test-Path -LiteralPath $psRegPath
        $coveredByScript = ($covered.Keys | Where-Object { $_ -eq $expanded.ToLowerInvariant() }).Count -gt 0
    }
    elseif ($expanded -like '*`**' -or $expanded -like '*[*]*') {
        # Wildcard advisory item.
        $parent = Split-Path -Parent $expanded
        $leaf = Split-Path -Leaf $expanded
        if (Test-Path -LiteralPath $parent) {
            $matches = @(Get-ChildItem -LiteralPath $parent -Force -ErrorAction SilentlyContinue | Where-Object { $_.Name -like $leaf })
            $exists = $matches.Count -gt 0
            $children = @($matches | Select-Object -First 10 | ForEach-Object { $_.FullName })
            $size = 0L
            foreach ($m in $matches) { $s = Get-DirectorySize -Path $m.FullName; if ($null -ne $s) { $size += $s } }
            $lastWrite = ($matches | Sort-Object LastWriteTime -Descending | Select-Object -First 1).LastWriteTime
        }
    }
    else {
        $exists = Test-Path -LiteralPath $expanded
        if ($exists) {
            $item = Get-Item -LiteralPath $expanded -Force -ErrorAction SilentlyContinue
            $lastWrite = $item.LastWriteTime
            $size = Get-DirectorySize -Path $expanded
            $children = Get-InterestingChildren -Path $expanded
        }

        $key = $expanded.TrimEnd('\').ToLowerInvariant()
        if ($covered.ContainsKey($key)) {
            $coveredByScript = $true
            $coveredRaw = $covered[$key]
        }
    }

    $large = ($null -ne $size -and $size -gt ($LargeThresholdMB * 1MB))
    $effectiveRecommendation = $c.Recommendation
    if ($coveredByScript -and $effectiveRecommendation -ne "Avoid") {
        $effectiveRecommendation = "AlreadyCovered"
    }
    elseif (-not $exists -and $effectiveRecommendation -eq "Add") {
        $effectiveRecommendation = "Consider"
    }
    elseif ($large -and $effectiveRecommendation -eq "Add") {
        $effectiveRecommendation = "Manual"
    }

    $results += [pscustomobject]@{
        Category = $c.Category
        Name = $c.Name
        Path = $c.Path
        ExpandedPath = $expanded
        Exists = $exists
        SizeBytes = $size
        Size = Format-Bytes $size
        LastWriteTime = $lastWrite
        Sensitive = $c.Sensitive
        Large = $large
        AlreadyCovered = $coveredByScript
        CoveredAs = $coveredRaw
        Recommendation = $effectiveRecommendation
        Why = $c.Why
        RestoreNote = $c.RestoreNote
        EvidenceHint = $c.EvidenceHint
        InterestingChildren = $children
    }
}

# Optional live inventories. These are metadata only.
$inventories = [ordered]@{}
if (Get-Command code.cmd -ErrorAction SilentlyContinue) {
    try { $inventories["VS Code extensions"] = @(& code.cmd --list-extensions 2>$null | Sort-Object) } catch {}
}
elseif (Get-Command code.exe -ErrorAction SilentlyContinue) {
    try { $inventories["VS Code extensions"] = @(& code.exe --list-extensions 2>$null | Sort-Object) } catch {}
}

if (Get-Command choco.exe -ErrorAction SilentlyContinue) {
    try { $inventories["Chocolatey packages"] = @(& choco.exe list --local-only 2>$null | Select-Object -First 200) } catch {}
}

if (Get-Command winget.exe -ErrorAction SilentlyContinue) {
    try { $inventories["Winget packages"] = @(& winget.exe list 2>$null | Select-Object -First 200) } catch {}
}

if (Get-Command wsl.exe -ErrorAction SilentlyContinue) {
    try { $inventories["WSL distros"] = @(& wsl.exe --list --verbose 2>$null) } catch {}
}

function Add-Line {
    param([System.Collections.Generic.List[string]]$Lines, [string]$Text = "")
    $Lines.Add($Text) | Out-Null
}

$lines = [System.Collections.Generic.List[string]]::new()
Add-Line $lines "# ChatGPT advisory: user-preference backup mining"
Add-Line $lines
Add-Line $lines "Generated: $(Get-Date -Format o)"
Add-Line $lines
Add-Line $lines "This report is based on path existence, sizes, timestamps, and selected filenames. It does **not** copy files and does **not** print secret contents."
Add-Line $lines
Add-Line $lines "## Summary"
Add-Line $lines
$found = @($results | Where-Object Exists)
$missing = @($results | Where-Object { -not $_.Exists })
$add = @($results | Where-Object { $_.Exists -and $_.Recommendation -eq "Add" })
$consider = @($results | Where-Object { $_.Exists -and $_.Recommendation -eq "Consider" })
$manual = @($results | Where-Object { $_.Exists -and $_.Recommendation -eq "Manual" })
$coveredFound = @($results | Where-Object { $_.Exists -and $_.AlreadyCovered })
$sensitiveFound = @($results | Where-Object { $_.Exists -and $_.Sensitive })
$largeFound = @($results | Where-Object { $_.Exists -and $_.Large })

Add-Line $lines "- Candidates checked: $($results.Count)"
Add-Line $lines "- Existing candidates: $($found.Count)"
Add-Line $lines "- Already covered by backup.ps1: $($coveredFound.Count)"
Add-Line $lines "- Recommended to add now: $($add.Count)"
Add-Line $lines "- Worth considering: $($consider.Count)"
Add-Line $lines "- Manual/large/special handling: $($manual.Count)"
Add-Line $lines "- Sensitive existing locations: $($sensitiveFound.Count)"
Add-Line $lines "- Large existing locations over $LargeThresholdMB MB: $($largeFound.Count)"
Add-Line $lines
Add-Line $lines "## Highest-value additions found"
Add-Line $lines
if ($add.Count -eq 0) {
    Add-Line $lines "No existing high-confidence additions were found."
} else {
    Add-Line $lines "| Category | Name | Path | Size | Sensitive | Why |"
    Add-Line $lines "|---|---|---|---:|:---:|---|"
    foreach ($r in ($add | Sort-Object Category, Name)) {
        Add-Line $lines ("| {0} | {1} | `{2}` | {3} | {4} | {5} |" -f
            (ConvertTo-MarkdownSafe $r.Category),
            (ConvertTo-MarkdownSafe $r.Name),
            (ConvertTo-MarkdownSafe $r.Path),
            $r.Size,
            ($(if ($r.Sensitive) { "yes" } else { "no" })),
            (ConvertTo-MarkdownSafe $r.Why)
        )
    }
}
Add-Line $lines

Add-Line $lines "## Consider / inspect before adding"
Add-Line $lines
if ($consider.Count -eq 0) {
    Add-Line $lines "No existing consider-level items were found."
} else {
    Add-Line $lines "| Category | Name | Path | Size | Sensitive | Why |"
    Add-Line $lines "|---|---|---|---:|:---:|---|"
    foreach ($r in ($consider | Sort-Object Category, Name)) {
        Add-Line $lines ("| {0} | {1} | `{2}` | {3} | {4} | {5} |" -f
            (ConvertTo-MarkdownSafe $r.Category),
            (ConvertTo-MarkdownSafe $r.Name),
            (ConvertTo-MarkdownSafe $r.Path),
            $r.Size,
            ($(if ($r.Sensitive) { "yes" } else { "no" })),
            (ConvertTo-MarkdownSafe $r.Why)
        )
    }
}
Add-Line $lines

Add-Line $lines "## Manual, large, or special-case items"
Add-Line $lines
if ($manual.Count -eq 0) {
    Add-Line $lines "No existing manual/special items were found."
} else {
    Add-Line $lines "| Category | Name | Path | Size | Sensitive | Restore note |"
    Add-Line $lines "|---|---|---|---:|:---:|---|"
    foreach ($r in ($manual | Sort-Object Category, Name)) {
        Add-Line $lines ("| {0} | {1} | `{2}` | {3} | {4} | {5} |" -f
            (ConvertTo-MarkdownSafe $r.Category),
            (ConvertTo-MarkdownSafe $r.Name),
            (ConvertTo-MarkdownSafe $r.Path),
            $r.Size,
            ($(if ($r.Sensitive) { "yes" } else { "no" })),
            (ConvertTo-MarkdownSafe $r.RestoreNote)
        )
    }
}
Add-Line $lines

Add-Line $lines "## Already covered and found"
Add-Line $lines
if ($coveredFound.Count -eq 0) {
    Add-Line $lines "No existing already-covered items were detected. Check BackupScriptPath if this is unexpected."
} else {
    Add-Line $lines "| Category | Name | Path | Size | Sensitive |"
    Add-Line $lines "|---|---|---|---:|:---:|"
    foreach ($r in ($coveredFound | Sort-Object Category, Name)) {
        Add-Line $lines ("| {0} | {1} | `{2}` | {3} | {4} |" -f
            (ConvertTo-MarkdownSafe $r.Category),
            (ConvertTo-MarkdownSafe $r.Name),
            (ConvertTo-MarkdownSafe $r.Path),
            $r.Size,
            ($(if ($r.Sensitive) { "yes" } else { "no" }))
        )
    }
}
Add-Line $lines

Add-Line $lines "## Detail by category"
Add-Line $lines
foreach ($cat in ($results.Category | Sort-Object -Unique)) {
    Add-Line $lines "### $cat"
    Add-Line $lines
    Add-Line $lines "| Status | Recommendation | Name | Path | Size | Last modified | Sensitive | Notes |"
    Add-Line $lines "|---|---|---|---|---:|---|:---:|---|"
    foreach ($r in ($results | Where-Object Category -eq $cat | Sort-Object Name)) {
        $status = if ($r.Exists) { "found" } else { "missing" }
        $last = if ($r.LastWriteTime) { $r.LastWriteTime.ToString("yyyy-MM-dd HH:mm") } else { "" }
        $notes = $r.Why
        if ($r.Large) { $notes += " Large: prefer opt-in/manual backup." }
        if ($r.AlreadyCovered) { $notes += " Already covered by backup.ps1." }
        Add-Line $lines ("| {0} | {1} | {2} | `{3}` | {4} | {5} | {6} | {7} |" -f
            $status,
            $r.Recommendation,
            (ConvertTo-MarkdownSafe $r.Name),
            (ConvertTo-MarkdownSafe $r.Path),
            $r.Size,
            $last,
            ($(if ($r.Sensitive) { "yes" } else { "no" })),
            (ConvertTo-MarkdownSafe $notes)
        )
    }
    Add-Line $lines
}

Add-Line $lines "## Interesting children from found directories"
Add-Line $lines
Add-Line $lines "This section lists names only, not contents. It helps distinguish custom preference files from caches."
Add-Line $lines
foreach ($r in ($found | Where-Object { $_.InterestingChildren.Count -gt 0 } | Sort-Object Category, Name)) {
    Add-Line $lines
    Add-Line $lines "### $($r.Name)"
    Add-Line $lines
    Add-Line $lines ('- Path: `' + (ConvertTo-MarkdownSafe $r.Path) + '`')
    Add-Line $lines "- Recommendation: $($r.Recommendation)"
    Add-Line $lines "- Children:"
    foreach ($child in $r.InterestingChildren) {
        if (-not $IncludeSensitiveDetails -and $r.Sensitive) {
            Add-Line $lines "  - [hidden because location is marked sensitive; rerun with -IncludeSensitiveDetails to show names only]"
            break
        }
        Add-Line $lines ('  - `' + (ConvertTo-MarkdownSafe $child) + '`')
    }
}
Add-Line $lines

Add-Line $lines "## Inventories"
Add-Line $lines
Add-Line $lines "These are useful for reconstruction and usually better than copying program folders."
foreach ($key in $inventories.Keys) {
    Add-Line $lines
    Add-Line $lines "### $key"
    Add-Line $lines
    if ($inventories[$key].Count -eq 0) {
        Add-Line $lines "No data captured."
    } else {
        Add-Line $lines '```text'
        foreach ($line in $inventories[$key]) {
            Add-Line $lines $line
        }
        Add-Line $lines '```'
    }
}

Add-Line $lines
Add-Line $lines "## Suggested backup.ps1 changes"
Add-Line $lines
Add-Line $lines "Review before applying. Sensitive paths should only go to encrypted backups."
Add-Line $lines
Add-Line $lines '```powershell'
foreach ($r in ($add | Sort-Object Category, Name)) {
    if ($r.Path.StartsWith("REG:")) { continue }
    Add-Line $lines ('Copy-BackupItem -Source "{0}" -RootName "user-preferences"' -f $r.Path)
}
Add-Line $lines '```'

Add-Line $lines
Add-Line $lines "## Suggested inventory commands"
Add-Line $lines
Add-Line $lines '```powershell'
Add-Line $lines 'New-Item -ItemType Directory -Force -Path "$env:USERPROFILE\dev-setup" | Out-Null'
Add-Line $lines 'if (Get-Command code -ErrorAction SilentlyContinue) { code --list-extensions | Sort-Object | Set-Content "$env:USERPROFILE\dev-setup\vscode-extensions.txt" -Encoding UTF8 }'
Add-Line $lines 'if (Get-Command pyenv -ErrorAction SilentlyContinue) { pyenv versions | Set-Content "$env:USERPROFILE\dev-setup\pyenv-versions.txt" -Encoding UTF8 }'
Add-Line $lines 'if (Get-Command pdm -ErrorAction SilentlyContinue) { pdm --version | Set-Content "$env:USERPROFILE\dev-setup\pdm-version.txt" -Encoding UTF8 }'
Add-Line $lines 'if (Get-Command gh -ErrorAction SilentlyContinue) { gh auth status 2>&1 | Set-Content "$env:USERPROFILE\dev-setup\gh-auth-status.txt" -Encoding UTF8 }'
Add-Line $lines '```'

Add-Line $lines
Add-Line $lines "## Caution"
Add-Line $lines
Add-Line $lines "- Do not upload this report publicly if `-IncludeSensitiveDetails` was used."
Add-Line $lines "- Backups containing SSH, cloud CLI, rclone, Docker, database, VPN, WinAuth, or AI assistant auth state should be encrypted."
Add-Line $lines "- Avoid restoring large app state blindly across Windows versions; prefer explicit import/export when available."

New-Item -ItemType Directory -Force -Path (Split-Path -Parent $OutputPath) | Out-Null
$lines | Set-Content -LiteralPath $OutputPath -Encoding UTF8

Write-Host "Wrote advisory: $OutputPath"
Write-Host "Found $($found.Count) existing candidates; $($add.Count) high-confidence additions; $($consider.Count) consider-level items."
